

spring:
  application:
    name: spring security
  security:
    user:
      name: user
      roles: user
  server:
    port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/dmswjd
    username: dmswjd

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
